# Page enumerators
MAIN_PAGE           = 0
TRJSTD_START_PAGE   = 1
TRJWRT_PAGE         = 2
SETTINGS_PAGE       = 3
TRJSTDCRT_PAGE      = 4

# Page events
NULL_EVENT              = -1

MAIN_PAGE_APP_DESTROY   = 0
MAIN_PAGE_TRJSTD        = 1
MAIN_PAGE_TRJWRT        = 2
MAIN_PAGE_SETTINGS      = 3

TRJSTD_START_PAGE_BACK      = 0
TRJSTD_START_PAGE_CRTTRJ    = 1
TRJSTD_START_PAGE_EDTTRJ    = 2

TRJWRT_PAGE_BACK    = 0
TRJWRT_PAGE_WRITE   = 1

SETTINGS_PAGE_BACK  = 0

TRJSTDCRT_PAGE_BACK = 0
TRJSTDCRT_PAGE_OK   = 1